In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import os
from datetime import datetime
import re
from sqlalchemy import create_engine

In [7]:
BASE_URL = "https://books.toscrape.com/catalogue/page-{}.html"
RATING_MAP = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}

In [15]:
def safe_get(url, delay=1):
    """Safe get with retry logic for error handling"""
    try:
            response = requests.get(url, timeout=10)
            response.raise_for_status
            time.sleep(delay)
            return response
    except requests.RequestException as e:
            print(f"Request: {e}")
            return None

In [16]:
#  Scrape 10 Pages
all_books = []

for page_num in range(1, 11):
    url = BASE_URL.format(page_num)
    print(f"Scraping page {page_num}: {url}")

    resp = safe_get(url)
    if not resp:
        continue

    soup = BeautifulSoup(resp.content, 'lxml')
    books = soup.select('article.product_pod')

    for book in books:
        title = book.h3.a['title']
        price_raw = book.select_one('p.price_color').text # e.g., £51.77
        rating_raw = book.select_one('p.star-rating')['class'][1] # e.g., Three
        availability = book.select_one('p.instock.availability').text.strip()
        product_url = "https://books.toscrape.com/catalogue/" + book.h3.a['href']

        all_books.append({
            "title": title,
            "price": price_raw,
            "rating": rating_raw,
            "availability": availability,
            "product_url": product_url,
            "page_number": page_num,
            "scraped_at": datetime.now()
        })

    time.sleep(1) # Respect the site

Scraping page 1: https://books.toscrape.com/catalogue/page-1.html
Scraping page 2: https://books.toscrape.com/catalogue/page-2.html
Scraping page 3: https://books.toscrape.com/catalogue/page-3.html
Scraping page 4: https://books.toscrape.com/catalogue/page-4.html
Scraping page 5: https://books.toscrape.com/catalogue/page-5.html
Scraping page 6: https://books.toscrape.com/catalogue/page-6.html
Scraping page 7: https://books.toscrape.com/catalogue/page-7.html
Scraping page 8: https://books.toscrape.com/catalogue/page-8.html
Scraping page 9: https://books.toscrape.com/catalogue/page-9.html
Scraping page 10: https://books.toscrape.com/catalogue/page-10.html

In [17]:
#  Build Raw DataFrame
df_raw = pd.DataFrame(all_books)
print(f"Raw shape: {df_raw.shape}") # Should be 200 rows x 7 cols, but 5 raw cols before cleaning
print(df_raw.head())

Raw shape: (200, 7)
                                   title   price rating availability  \
0                   A Light in the Attic  £51.77  Three     In stock
1                     Tipping the Velvet  £53.74    One     In stock
2                             Soumission  £50.10    One     In stock
3                          Sharp Objects  £47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  £54.23   Five     In stock

                                         product_url  page_number  \
0  https://books.toscrape.com/catalogue/a-light-i...            1
1  https://books.toscrape.com/catalogue/tipping-t...            1
2  https://books.toscrape.com/catalogue/soumissio...            1
3  https://books.toscrape.com/catalogue/sharp-obj...            1
4  https://books.toscrape.com/catalogue/sapiens-a...            1

                  scraped_at
0 2026-09-30 22:37:49.170699
1 2026-09-30 22:37:49.170957
2 2026-09-30 22:37:49.171203
3 2026-09-30 22:37:49.171442
4 2026-09-30 22:37:49.171693

In [18]:
#  Clean & Transform
df = df_raw.copy()

# price -> NUMERIC (strip encoding)
df['price'] = df['price'].str.replace('£', '', regex=False).str.replace('Â', '', regex=False).astype(float)

# rating -> INTEGER (word-to-number map)
df['rating'] = df['rating'].map(RATING_MAP).astype(int)

# Clean availability to just get stock count if needed
# df['availability'] remains as string

print(f"Cleaned shape: {df.shape}")
print(df.dtypes)
df.head()

Cleaned shape: (200, 7)
title                   object
price                  float64
rating                   int64
availability            object
product_url             object
page_number              int64
scraped_at      datetime64[ns]
dtype: object

,title,price,rating,availability,product_url,page_number,scraped_at
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...,1,2026-09-30 22:37:49.170699
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...,1,2026-09-30 22:37:49.170957
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...,1,2026-09-30 22:37:49.171203
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...,1,2026-09-30 22:37:49.171442
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...,1,2026-09-30 22:37:49.171693

In [13]:
# Load to PostgreSQL
#from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = "1980Theo@"  # your real password
encoded_pwd = "1980Theo%40"

engine = create_engine(f"postgresql+psycopg2://postgres:{encoded_pwd}@localhost:5432/webscraping_proj_1")

try:
    with engine.connect() as connection:
        print("Database connection established successfully!")
except Exception as e:
    print("Connection failed:", e)

Database connection established successfully!

In [14]:
# Load
df.to_sql("books_catalogue", engine, if_exists="replace", index=False)
print("Loaded to PostgreSQL")

# Confirm row count
check_df = pd.read_sql("SELECT COUNT(*) FROM books_catalogue", engine)
print(check_df)

check_df2 = pd.read_sql("SELECT * FROM books_catalogue LIMIT 5", engine)
check_df2

Loaded to PostgreSQL
   count
0    200

,title,price,rating,availability,product_url,page_number,scraped_at
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...,1,2026-09-30 21:16:31.112724
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...,1,2026-09-30 21:16:31.112927
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...,1,2026-09-30 21:16:31.113117
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...,1,2026-09-30 21:16:31.113307
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...,1,2026-09-30 21:16:31.113496